version: "3.8"

services:
    mysql:
        image: mysql:8.0
        container_name: players_mysql
        environment:
            MYSQL_DATABASE: players
            MYSQL_ROOT_PASSWORD: FootBall123
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
            interval: 10s
            start_period: 40s

    backend:
        build:
            context: ./Backend
            dockerfile: Dockerfile
        container_name: players_backend
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/players
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: FootBall123
        ports:
            - "8080:8080"
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - app-network
        restart: on-failure

    frontend:
        build:
            context: ./Frontend
            dockerfile: Dockerfile
        container_name: players_frontend
        ports:
            - "3000:80"
        depends_on:
            - backend
        networks:
            - app-network

volumes:
    mysql_data:

networks:
    app-network:
        driver: bridge
